spring.application.name=truck-dispatch
server.port=8080

# H2 file-based baza (ostaje izmedju restartova)
spring.datasource.url=jdbc:h2:file:./truck-dispatch-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 konzola dostupna na http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
